name: homelab-monitor

services:
  api:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:mode=1777

  dashboard:
    ports:
      - "127.0.0.1:80:8080"
    read_only: true
    tmpfs:
      - /tmp:mode=1777
      - /var/cache/nginx:mode=1777
      - /var/run:mode=1777
      - /var/log/nginx:mode=1777
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
